services:
  web:
    container_name: coffee_app
    image: coffee-app-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload"
        
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: "no"
    networks:
      - coffee_net

  db:
    container_name: coffee_db
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - coffee_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "no"
    networks:
      - coffee_net

  redis:
    container_name: coffee_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "no"
    networks:
      - coffee_net

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks.celery.celery_app worker -l info --concurrency=4
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - coffee_net

  beat:
    build: .
    container_name: celery_beat
    command: celery -A app.tasks.celery.celery_app beat --loglevel=info
    depends_on:
      - worker
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - coffee_net

volumes:
  coffee_db_data:
    name: coffee_db_data

networks:
  coffee_net:
    driver: bridge